### 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Administrator",
    "email": "admin@admin.com",
    "pass": "Chilaquiles123",
    "age": 20,
    "employment": "Admin",
    "phone": "1234567890"
}

### 
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@correo.com",
    "pass": "password",
    "age": 20,
    "employment": "x",
    "phone": "1234567890"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "pass": "Chilaquiles123"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@correo.com",
    "pass": "password"
}

###
POST http://localhost:3000/product/
Content-Type: application/json
auth: Admin

{
    "imageURL": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.c",
    "name": "test",
    "description": "test",
    "price": 100
}

###
POST http://localhost:3000/sale/
Content-Type: application/json

{
  "products": [
    {
      "productId": "615a7cd3d36a63462e4e106e",
      "quantity": 3,
      "price": 25
    },
    {
      "productId": "615a7cd3d36a63462e4e106f",
      "quantity": 1,
      "price": 50
    }
  ],
  "datetime": "2023-11-22T08:00:00Z",
  "vendor": "Nombre del vendedor",
  "paymentMethod": "Efectivo",
  "advance": 100,
  "extraCost": 10,
  "comments": "Comentario opcional",
  "subtotal": 115,
  "total": 125
}
